In [5]:
# importing numpy module
import numpy as np
list=[5,6,7,8]
sample_array = np.array([1,2,3,4])
print("List in python : ", list)
print("Numpy Array in python :", sample_array)

List in python :  [5, 6, 7, 8]
Numpy Array in python : [1 2 3 4]


In [6]:
# importing numpy module
import numpy as np
# creating list
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
# creating numpy array
sample_array = np.array([list_1, list_2, list_3])
print("Numpy multi dimensional array in python\n", sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
